# Generated by Django 5.2.5 on 2025-08-20 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('libelle', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Departements',
                'verbose_name_plural': 'Departements',
                'db_table': 'departements',
            },
        ),
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('libelle', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Quartiers',
                'verbose_name_plural': 'Quartiers',
                'db_table': 'quartiers',
            },
        ),
        migrations.CreateModel(
            name='Tribu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('libelle', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Tribus',
                'verbose_name_plural': 'Tribus',
                'db_table': 'tribus',
            },
        ),
        migrations.CreateModel(
            name='TypeCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('libelle', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Types de cours',
                'verbose_name_plural': 'Types de cours',
                'db_table': 'type_cours',
            },
        ),
    ]
