# Generated by Django 5.2.5 on 2025-08-20 01:42

import session.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('numero_certificat', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('date_debut_validite', models.DateField(blank=True, null=True)),
                ('date_fin_validite', models.DateField(blank=True, null=True)),
                ('date_utilisation', models.DateField(blank=True, null=True)),
                ('statut_certificat', models.CharField(choices=[('Disponible', 'Disponible'), ('Non disponible', 'Non Disponible')], default='Disponible', max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Certificats',
                'verbose_name_plural': 'Certificats',
                'db_table': 'certificats',
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('titre', models.CharField(blank=True, max_length=50, null=True)),
                ('sous_titre', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_publication', models.DateField(blank=True, null=True)),
                ('cours_video', models.ImageField(blank=True, null=True, upload_to=session.models.upload_videos)),
                ('cours_audio', models.ImageField(blank=True, null=True, upload_to=session.models.upload_audios)),
                ('cours_texte', models.ImageField(blank=True, null=True, upload_to=session.models.upload_textes)),
                ('statut_cours', models.CharField(choices=[('En cours', 'Encours'), ('Terminé', 'Termine')], default='En cours', max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'db_table': 'cours',
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('statut_inscription', models.CharField(choices=[('En cours', 'Encours'), ('Terminé', 'Termine')], default='En cours', max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Inscriptions',
                'verbose_name_plural': 'Inscriptions',
                'db_table': 'inscriptions',
            },
        ),
        migrations.CreateModel(
            name='ParticipationCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('statut_participation', models.CharField(choices=[('En cours', 'Encours'), ('Terminé', 'Termine')], default='En cours', max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Participations Cours',
                'verbose_name_plural': 'Participations Cours',
                'db_table': 'participation_cours',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('libelle', models.CharField(blank=True, max_length=50, null=True)),
                ('date_publication', models.DateField(blank=True, null=True)),
                ('point', models.IntegerField(null=True)),
                ('statut_question', models.CharField(choices=[('Brouillon', 'Brouillon'), ('Validé', 'Valide'), ('Supprimé', 'Supprime'), ('En Attente', 'Enattente')], default='Validé', max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Questions',
                'verbose_name_plural': 'Questions',
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('libelle', models.CharField(blank=True, max_length=50, null=True)),
                ('date_publication', models.DateField(blank=True, null=True)),
                ('statut_reponse', models.CharField(choices=[('Vrai', 'Vrai'), ('Faux', 'Faux')], default='Vrai', max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Reponses',
                'verbose_name_plural': 'Reponses',
                'db_table': 'reponses',
            },
        ),
        migrations.CreateModel(
            name='ReponseUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date_heure_debut', models.DateTimeField(blank=True, null=True)),
                ('date_heure_fin', models.DateTimeField(blank=True, null=True)),
                ('point_acquis', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Reponses Utilisateurs',
                'verbose_name_plural': 'Reponses Utilisateurs',
                'db_table': 'reponse_utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_publication', models.DateField(blank=True, null=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('statut_session', models.CharField(choices=[('En cours', 'Encours'), ('Terminé', 'Termine')], default='En cours', max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Sessions',
                'verbose_name_plural': 'Sessions',
                'db_table': 'sessions',
            },
        ),
    ]
