# Generated by Django 5.2.5 on 2025-08-20 01:42

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import utilisateur.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('parametre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nom', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('prenoms', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('autre_telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('date_naissance', models.CharField(blank=True, max_length=20, null=True)),
                ('situation_matrimoniale', models.CharField(choices=[('Célibataire', 'Celibataire'), ('Concubinage', 'Concubinage'), ('Divorcé(e)', 'Divorce'), ('Marié(e)', 'Marie'), ('Veuf(ve)', 'Veuf')], default='Célibataire', max_length=20, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=utilisateur.models.upload_photo)),
                ('statut_compte', models.CharField(choices=[('Activé', 'Active'), ('Désactivé', 'Desactive'), ('Fermé', 'Ferme'), ('Bloqué', 'Bloque')], default='Activé', max_length=20, null=True)),
                ('departement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='parametre.departement')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('quartier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='parametre.quartier')),
                ('tribu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='parametre.tribu')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateurs',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'utilisateur',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
